{
  "props": {
    "author": "queinu",
    "version": "2.5.2",
    "description": "OFLL Initialization Module",
    "singleton": true
  },
  "components": {
    "launcher": {
      "type": "script\\storage\\IniStorage",
      "x": 80,
      "y": 16,
      "props": {
        "path": "",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    },
    "games": {
      "type": "script\\storage\\IniStorage",
      "x": 16,
      "y": 16,
      "props": {
        "path": "",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    }
  }
}