{
  "props": [],
  "components": {
    "settings": {
      "type": "script\\storage\\IniStorage",
      "x": 80,
      "y": 16,
      "props": {
        "path": "",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    },
    "overlayEmulator": {
      "type": "script\\HotKeyScript",
      "x": 240,
      "y": 16,
      "props": {
        "disabled": false,
        "key": "shift + tab"
      }
    },
    "games": {
      "type": "script\\storage\\IniStorage",
      "x": 16,
      "y": 16,
      "props": {
        "path": "",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    }
  }
}